name: Deploy to Google Cloud
on:
  push:
    branches:
      - master
steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up Google Cloud SDK
    uses: google-github-actions/setup-gcloud@master
    with:
      version: latest
      service_account_key: ${{ secrets.GCP_SA_KEY }}
  - name: Deploy to Google Cloud
    uses: google-github-actions/gcloud-app-deploy@master
    with:
      project_id: my-gcp-project-id
      version: '${{ env.TAG_NAME }}'
      image: 'gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}'
      env_vars: |
        KEY1=value1
        KEY2=value2
